# -*- coding: utf-8 -*-
"""cvd_pred_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oq200ky5EbsR1AkIt6CasMtnv_QJFjHe
"""

import streamlit as st
import pickle
import pandas as pd

# Load saved model and feature list
with open("cvd_logistic_predictor.sav", "rb") as file:
    model = pickle.load(file)

with open("cvd_features.sav", "rb") as file:
    selected_features = pickle.load(file)


def predict_cvd(model, input_df):
    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1]

    if prediction == 1:
        return "Higher CVD Risk", probability
    else:
        return "Lower CVD Risk", probability


def main():
    st.title("Cardiovascular Event Risk Predictor")
    st.write("Enter patient health, demographic, and sleep information below.")

    # -----------------------------
    # Demographics
    # -----------------------------
    st.header("Demographics")

    age_s1 = st.number_input("Age", min_value=40, max_value=100, value=60)

    gender = st.radio("Gender", ["Male", "Female"])
    gender_2 = 1 if gender == "Female" else 0

    race = st.selectbox(
        "Race Category",
        ["Race 1 / Reference Group", "Race 2", "Other"]
    )
    race_2 = 1 if race == "Race 2" else 0

    # -----------------------------
    # Body and cardiovascular health
    # -----------------------------
    st.header("Health Indicators")

    bmi_s1 = st.number_input("BMI", min_value=10.0, max_value=70.0, value=28.0)
    waist = st.number_input("Waist Circumference", min_value=40.0, max_value=200.0, value=95.0)

    SystBP = st.number_input("Systolic Blood Pressure", min_value=80, max_value=250, value=130)
    Chol = st.number_input("Total Cholesterol", min_value=80, max_value=400, value=200)
    HDL = st.number_input("HDL Cholesterol", min_value=10, max_value=150, value=50)
    Trig = st.number_input("Triglycerides", min_value=20, max_value=600, value=150)

    hypertension = st.radio("History of Hypertension?", ["No", "Yes"])
    SRHype_1 = 1 if hypertension == "Yes" else 0

    diabetes = st.radio("History of Diabetes?", ["No", "Yes"])
    ParRptDiab_1 = 1 if diabetes == "Yes" else 0

    # -----------------------------
    # Lifestyle
    # -----------------------------
    st.header("Lifestyle")

    CgPkYr = st.number_input("Smoking Pack-Years", min_value=0.0, max_value=150.0, value=0.0)

    current_smoker = st.radio("Current Smoker?", ["No", "Yes"])
    smokstat_s1_1 = 1 if current_smoker == "Yes" else 0

    alcoh_drinks = st.number_input("Alcohol Drinks per Week", min_value=0.0, max_value=100.0, value=0.0)

    # -----------------------------
    # Sleep metrics
    # -----------------------------
    st.header("Sleep Metrics")

    slp_rdi = st.number_input("Sleep RDI / Apnea Severity", min_value=0.0, max_value=120.0, value=10.0)
    slp_eff = st.number_input("Sleep Efficiency (%)", min_value=0.0, max_value=100.0, value=85.0)
    pctlt90 = st.number_input("% Sleep Time with Oxygen Saturation < 90%", min_value=0.0, max_value=100.0, value=2.0)

    # Prepare input data in exact model order
    input_data = pd.DataFrame([{
        "age_s1": age_s1,
        "gender_2": gender_2,
        "race_2": race_2,
        "bmi_s1": bmi_s1,
        "waist": waist,
        "SystBP": SystBP,
        "Chol": Chol,
        "HDL": HDL,
        "Trig": Trig,
        "SRHype_1.0": SRHype_1,
        "ParRptDiab_1.0": ParRptDiab_1,
        "CgPkYr": CgPkYr,
        "smokstat_s1_1.0": smokstat_s1_1,
        "alcoh_drinks": alcoh_drinks,
        "slp_rdi": slp_rdi,
        "slp_eff": slp_eff,
        "pctlt90": pctlt90
    }])

    input_data = input_data[selected_features]

    if st.button("Predict CVD Risk"):
        result, probability = predict_cvd(model, input_data)

        st.subheader("Prediction Result")
        st.write(f"Prediction: **{result}**")
        st.write(f"Estimated Probability of CVD Event: **{probability:.2%}**")

        if probability >= 0.50:
            st.warning("The model classifies this patient as higher risk.")
        else:
            st.success("The model classifies this patient as lower risk.")

    st.caption("This tool is for academic demonstration only and is not medical advice.")


if __name__ == "__main__":
    main()